
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 7;
  public static final int PAR_DCHA = 20;
  public static final int INTERSECCION = 6;
  public static final int FLECHA = 10;
  public static final int OPERA = 3;
  public static final int ID = 12;
  public static final int DOS_PUNTOS = 17;
  public static final int COMA = 18;
  public static final int EOF = 0;
  public static final int CONJ = 2;
  public static final int PAR_IZQ = 19;
  public static final int UNION = 5;
  public static final int error = 1;
  public static final int LLAVE_DCHA = 16;
  public static final int COMPLEMENTO = 8;
  public static final int LLAVE_IZQ = 15;
  public static final int PUNTO_COMA = 11;
  public static final int ASCII = 14;
  public static final int EVALUAR = 4;
  public static final int ENTERO = 13;
  public static final int RANGO = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "OPERA",
  "EVALUAR",
  "UNION",
  "INTERSECCION",
  "DIFERENCIA",
  "COMPLEMENTO",
  "RANGO",
  "FLECHA",
  "PUNTO_COMA",
  "ID",
  "ENTERO",
  "ASCII",
  "LLAVE_IZQ",
  "LLAVE_DCHA",
  "DOS_PUNTOS",
  "COMA",
  "PAR_IZQ",
  "PAR_DCHA"
  };
}

